runtime: custom
env: flex
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1
  cool_down_period_sec: 120
  cpu_utilization:
    target_utilization: 0.85
beta_settings:
  cloud_sql_instances: "mapmatical:us-central1:mapmatical-sql"
